In [32]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st

In [33]:
df = pd.read_csv(r"E:\Croma\Projects\Python Projects\Chrun Data Analysis\Datasets\Churn_Modelling.csv")

In [34]:
df.shape

(10000, 14)

In [35]:
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [36]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.2 MB

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
newdf = df.copy()

In [40]:

gender = st.selectbox("Select Gender" , newdf['Gender'].unique())

2026-07-24 02:12:03.795 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 02:12:03.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 02:12:03.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 02:12:03.824 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 02:12:03.826 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 02:12:03.829 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [41]:
newdf=newdf[newdf['Gender']==gender]

In [42]:
newdf.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [43]:
newdf.groupby('Geography')['Balance'].sum().reset_index()

  Geography       Balance
0    France  1.363896e+08
1   Germany  1.421411e+08
2     Spain  6.518982e+07

In [44]:
newdf.rename(columns={'Geography' : 'Country'})

,RowNumber,CustomerId,Surname,CreditScore,Country,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [46]:
newdf['Exited'] = newdf['Exited'].replace({
  0:'Stay connected',
  1:'Exited'
})

In [47]:
newdf.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,Exited
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,Stay connected
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,Exited
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,Stay connected
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,Stay connected

In [45]:
newdf.info()

<class 'pandas.DataFrame'>
Index: 4543 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        4543 non-null   int64
 1   CustomerId       4543 non-null   int64
 2   Surname          4543 non-null   str
 3   CreditScore      4543 non-null   int64
 4   Geography        4543 non-null   str
 5   Gender           4543 non-null   str
 6   Age              4543 non-null   int64
 7   Tenure           4543 non-null   int64
 8   Balance          4543 non-null   float64
 9   NumOfProducts    4543 non-null   int64
 10  HasCrCard        4543 non-null   int64
 11  IsActiveMember   4543 non-null   int64
 12  EstimatedSalary  4543 non-null   float64
 13  Exited           4543 non-null   int64
dtypes: float64(2), int64(9), str(3)
memory usage: 616.0 KB